### ISSUE TITLE
How to send something to device?

### ISSUE THREAD

**Issue by siadajpan** [alt236/Bluetooth-LE-Library---Android#14]
Can you explain what to use to send some data over BT?
Is it writing/reading characteristic that will do the trick?

Thanks

**Comment by yusufonderd** [comment]
1) Clone library
2) make BluetoothGatt private in BluetoothLeService
3) bleCharacteristic.setValue(ALERT_TYPE, BluetoothGattCharacteristic.FORMAT_UINT8, 0);
      mBluetoothLeService.mBluetoothGatt.writeCharacteristic(bleCharacteristic)
