### ISSUE TITLE
Bluetooth-LE-Library---Android Crashes

### ISSUE THREAD

**Issue by puzuwe** [alt236/Bluetooth-LE-Library---Android#16]
05-11 10:54:58.546 26445-26445/uk.co.alt236.btlescan E/libc++abi: terminating with uncaught exception of type std::bad_alloc: std::bad_alloc
05-11 10:54:58.546 26445-26445/uk.co.alt236.btlescan A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 26445 (alt236.btlescan)

**Comment by alt236** [comment]
Can you tell me what device this is on (model/type/os version/rooted) and what you were trying to do?

**Comment by puzuwe** [comment]
Device Name : Galaxy J5
Android version : 5.1.1
KNOX Version
Model Number : SM-J500FN

**Comment by leobeerg1** [comment]
Ddd
