### ISSUE TITLE
Android 6.0 not in LeScanCallback

### ISSUE THREAD

**Issue by WeberHsu** [alt236/Bluetooth-LE-Library---Android#17]
In Android 6.0 appear information log below:
D/BluetoothAdapter: startLeScan(): null
And the program not in LeScanCallback (onLeScan), what's wrong with it ?
thanks~

**Comment by alt236** [comment]
Have you granted your app the runtime permissions?

**Comment by WeberHsu** [comment]
Yes
2016/7/4 下午5:35於 "Alexandros Schillings" <notifications@github.com>寫道：

**Comment by WeberHsu** [comment]
I have set in the AndroidManifest.xml 
and bluetooth permission is not dangerous permission, and it can not be granted in runtime permission

**Comment by alt236** [comment]
Good point. 

Does the sample app work for you?

Also, what device are you using? Does it support BTLE?

**Comment by WeberHsu** [comment]
The app in play store is OK, my device is SONY Z5
I think it is support BTLE

**Comment by wdh-1025** [comment]
@WeberHsu Android 6.0 need to increase the "ACCESS_COARSE_LOCATION" permissions, and obtained the permission to ensure it

**Comment by alt236** [comment]
@wdh-1025 Good point. That is the solution for 6.0+.
