### ISSUE TITLE
Equipment is beside, "Distance" has 20 M

### ISSUE THREAD

**Issue by wdh-1025** [alt236/Bluetooth-LE-Library---Android#18]
Equipment is beside, "Distance" has 20 M

**Comment by alt236** [comment]
The thing to remember is that any distance calculation for beacons is generally innacurate. Mind you, 20m is a large error if the beacon is right next to you. 

This could be one of many things (or any/all of them simultaneously):

1. An error in the calculation formula
2. The reported calibration (txPower) by the beacon being wrong.
3. The beacon being set to transmit with _really_ low power which will make things more inaccurate.
