### ISSUE TITLE
Please add License to this project

### ISSUE THREAD

**Issue by shaik41** [alt236/Bluetooth-LE-Library---Android#44]
Hi Dev, 

Thank you for such a useful library, can you please add license details to this repo. Thank you

**Comment by alt236** [comment]
Hi, it's already licenced as Apache 2.0 (https://github.com/alt236/Bluetooth-LE-Library---Android/blob/master/LICENSE-2.0.html) but Github is not picking it up.

Let me have a look on why.

**Comment by alt236** [comment]
fixed now via #45
