### ISSUE TITLE
Some issue in GattAttributeResolver

### ISSUE THREAD

**Issue by greatwh** [alt236/Bluetooth-LE-Library---Android#9]
The service or characteristic id may have some error, for example:
public static final String LINK_LOSS = "00001804-0000-1000-8000-00805f9b34fb";
it should be 1803 for  LINK_LOSS

**Comment by alt236** [comment]
Yes, you are right. I will fix over the weekend.

**Comment by alt236** [comment]
The fix is now in Master, but not yet in the published app
